-- ozkey-13 §10 phase 4 / XF-69 §2 — S3: drop grants.raw_value
--
-- EXECUTED 2026-08-08. Kept as the historical record of the cutover, and
-- because `server.js`'s `initDatabase()` now folds this same ALTER in as an
-- idempotent boot-time migration (information_schema check + DROP COLUMN if
-- present) so every environment running this code converges to the same
-- schema, not just the one this file was run against by hand. Running this
-- file again is a harmless no-op once the column is already gone.
--
-- Preconditions that were confirmed before running it:
--   1. App builds send envelope_hex — ftpos shipped A1-A5 (issuePin/
--      revokeGrant sealing, directory_client.dart envelope_hex fields,
--      keyring.dart sealAddTempPin/sealDeleteRfid etc.), verified present in
--      the ftpos repo at cutover time.
--   2. Firmware accepts envelope_hex on the sealed path for both direct-WiFi
--      (F1-F5) and bridged Thread locks (F7 in ozdoorlock_core.h, BR1 in
--      bridge32.ino) — confirmed via live test: a sealed grant to bridged
--      lock ozk-b0a6048b5fd8 reached `status='sent'`, not stuck `queued`.
--   3. Operator instruction, explicit: "S3/S4 cutover – drop
--      grants.raw_value, delete buildCredentialFrame()".
--
-- Paired code change (S4, same date): buildCredentialFrame()/
-- buildDeleteFrame()/credentialValueBytes() deleted from server.js, and
-- POST/DELETE /locks/:id/grants now require envelope_hex — raw_value is no
-- longer accepted on either endpoint, not just deprioritized.
--
-- No legacy `raw_value` data survived this: at cutover time the `grants`
-- table held 3 rows, all already revoked, none `raw_value IS NOT NULL AND
-- sync_status = 'pending'` (checked live before running).

ALTER TABLE grants DROP COLUMN raw_value;
